
##
# Wild / RandomTP Config Section
##

# If this is set to true, we look for the minecraft worldborder. 
# Set to true ONLY if you have a MINECRAFT worldborder set, not a plugin border.
# Keep in mind, the minecraft default world border is 29,999,999.
#
# If this is set to false, the max-teleport-distance is used as the border ( minus 10% )
wild-use-worldborder: true

# Max distance from spawn
# This is ignored if use-worldborder is true.
wild-max-teleport-distance: 2500

# Use particle effects on-teleport.
# It works, but it's not fleshed out with any variability
wild-use-effects: false

# Seconds before someone can use /wild again
wild-command-cooldown: 30

# Seconds the player is immune from fall damage post-teleport.
wild-immunity-seconds: 60
